version: '3'

services:
  frontend:
    build: frontend
    ports:
      - 8501:8501
    depends_on:
      - model  # コンテナ名
    volumes:
      - ./storage:/storage
  model:
    build: api  # ディレクトリ名
    ports:
      - 8080:8080
    volumes:
      - ./storage:/storage